// <auto-generated />
using System;
using HeroesApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroesApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220308190626_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HeroesApi.Models.Heroes.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CurrentPower")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartedTrainingAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartingPower")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8fd13349-ee75-43b8-9c34-999cbafc2d8a"),
                            Ability = "Defender",
                            ApplicationUserId = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            CurrentPower = 46m,
                            Name = "Dr. Strange",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6798),
                            StartingPower = 46m
                        },
                        new
                        {
                            Id = new Guid("a4c95cf6-33db-4db9-b108-de76a0b5dce1"),
                            Ability = "Attacker",
                            ApplicationUserId = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            CurrentPower = 30m,
                            Name = "Deadpool",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6811),
                            StartingPower = 30m
                        },
                        new
                        {
                            Id = new Guid("9e349f66-9bd8-4ce4-bcd4-21213ce71dc6"),
                            Ability = "Defender",
                            ApplicationUserId = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            CurrentPower = 50m,
                            Name = "Thanos",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6823),
                            StartingPower = 50m
                        },
                        new
                        {
                            Id = new Guid("6d7819ca-efda-478e-ab81-0a545f4cc1e2"),
                            Ability = "Defender",
                            ApplicationUserId = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            CurrentPower = 35m,
                            Name = "Iron-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6831),
                            StartingPower = 35m
                        },
                        new
                        {
                            Id = new Guid("5731ae4e-fa73-47d9-8c20-9553d4b582ff"),
                            Ability = "Attacker",
                            ApplicationUserId = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            CurrentPower = 39m,
                            Name = "Captain America",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6901),
                            StartingPower = 39m
                        },
                        new
                        {
                            Id = new Guid("3a10bf79-85dd-4703-ab45-4f3ca23f4518"),
                            Ability = "Attacker",
                            ApplicationUserId = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            CurrentPower = 36m,
                            Name = "Thor",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6911),
                            StartingPower = 36m
                        },
                        new
                        {
                            Id = new Guid("a249ce29-a842-469e-bea6-63fc400d5897"),
                            Ability = "Attacker",
                            ApplicationUserId = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            CurrentPower = 49m,
                            Name = "Black Widow",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6920),
                            StartingPower = 49m
                        },
                        new
                        {
                            Id = new Guid("b4731181-eaf0-4c25-a0fb-e346979f8b13"),
                            Ability = "Attacker",
                            ApplicationUserId = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            CurrentPower = 36m,
                            Name = "Scarlet Witch",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6928),
                            StartingPower = 36m
                        },
                        new
                        {
                            Id = new Guid("9ca081c2-2be9-491b-9db0-973005b505a8"),
                            Ability = "Attacker",
                            ApplicationUserId = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            CurrentPower = 33m,
                            Name = "Captain Marvel",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6940),
                            StartingPower = 33m
                        },
                        new
                        {
                            Id = new Guid("5956738d-c40c-4995-bb5a-c69809b58f48"),
                            Ability = "Attacker",
                            ApplicationUserId = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            CurrentPower = 37m,
                            Name = "Pheonix",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6949),
                            StartingPower = 37m
                        },
                        new
                        {
                            Id = new Guid("4fb8ecbf-d8e7-427d-b80e-c330bc718ad4"),
                            Ability = "Defender",
                            ApplicationUserId = "49ba864d-5963-493f-8254-217192dfe74b",
                            CurrentPower = 48m,
                            Name = "Spider-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6958),
                            StartingPower = 48m
                        },
                        new
                        {
                            Id = new Guid("7140ca1f-ccce-42e3-aa5a-1df93e347c9c"),
                            Ability = "Attacker",
                            ApplicationUserId = "49ba864d-5963-493f-8254-217192dfe74b",
                            CurrentPower = 35m,
                            Name = "The Punisher",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6966),
                            StartingPower = 35m
                        },
                        new
                        {
                            Id = new Guid("e9c119f5-7cba-4c32-9326-478fccd7d90d"),
                            Ability = "Attacker",
                            ApplicationUserId = "49ba864d-5963-493f-8254-217192dfe74b",
                            CurrentPower = 33m,
                            Name = "The Hulk",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6974),
                            StartingPower = 33m
                        },
                        new
                        {
                            Id = new Guid("0631cff2-cbc8-4be7-a518-422b395183fc"),
                            Ability = "Defender",
                            ApplicationUserId = "49ba864d-5963-493f-8254-217192dfe74b",
                            CurrentPower = 48m,
                            Name = "Wolverine",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6982),
                            StartingPower = 48m
                        },
                        new
                        {
                            Id = new Guid("4bd00c16-d738-4acd-8c95-6e04483061d5"),
                            Ability = "Attacker",
                            ApplicationUserId = "49ba864d-5963-493f-8254-217192dfe74b",
                            CurrentPower = 35m,
                            Name = "Ant-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6991),
                            StartingPower = 35m
                        },
                        new
                        {
                            Id = new Guid("7297dc26-0268-4d58-af2e-3048e11fb473"),
                            Ability = "Defender",
                            ApplicationUserId = "49ba864d-5963-493f-8254-217192dfe74b",
                            CurrentPower = 39m,
                            Name = "Black Panther",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(6999),
                            StartingPower = 39m
                        },
                        new
                        {
                            Id = new Guid("9d61dd61-bf35-486a-9c47-3d6c849985b8"),
                            Ability = "Defender",
                            ApplicationUserId = "49ba864d-5963-493f-8254-217192dfe74b",
                            CurrentPower = 36m,
                            Name = "Venom",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7010),
                            StartingPower = 36m
                        },
                        new
                        {
                            Id = new Guid("e4838b46-c1f6-4c77-be4e-de7fe01675e6"),
                            Ability = "Attacker",
                            ApplicationUserId = "49ba864d-5963-493f-8254-217192dfe74b",
                            CurrentPower = 35m,
                            Name = "Star Lord",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7053),
                            StartingPower = 35m
                        },
                        new
                        {
                            Id = new Guid("9be7d241-b13b-4f2f-b565-9de69329a63a"),
                            Ability = "Attacker",
                            ApplicationUserId = "49ba864d-5963-493f-8254-217192dfe74b",
                            CurrentPower = 43m,
                            Name = "Super-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7061),
                            StartingPower = 43m
                        },
                        new
                        {
                            Id = new Guid("1d5e4f75-7a5e-477d-9487-353074933703"),
                            Ability = "Defender",
                            ApplicationUserId = "49ba864d-5963-493f-8254-217192dfe74b",
                            CurrentPower = 43m,
                            Name = "Bat-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7069),
                            StartingPower = 43m
                        },
                        new
                        {
                            Id = new Guid("4c939e82-0569-427d-8e86-776406cd0416"),
                            Ability = "Defender",
                            ApplicationUserId = "62029255-19a6-4583-bb55-1bd251999ff1",
                            CurrentPower = 49m,
                            Name = "The Joker",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7078),
                            StartingPower = 49m
                        },
                        new
                        {
                            Id = new Guid("6f8cdcfb-3378-49e2-b5c5-58768294f7b2"),
                            Ability = "Attacker",
                            ApplicationUserId = "62029255-19a6-4583-bb55-1bd251999ff1",
                            CurrentPower = 45m,
                            Name = "Bane",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7088),
                            StartingPower = 45m
                        },
                        new
                        {
                            Id = new Guid("34ac0bad-c01c-4b28-bb38-baa351aabd93"),
                            Ability = "Attacker",
                            ApplicationUserId = "62029255-19a6-4583-bb55-1bd251999ff1",
                            CurrentPower = 47m,
                            Name = "Wonder Woman",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7096),
                            StartingPower = 47m
                        },
                        new
                        {
                            Id = new Guid("071c7a42-11f8-4438-b737-b9bc6b04c989"),
                            Ability = "Defender",
                            ApplicationUserId = "62029255-19a6-4583-bb55-1bd251999ff1",
                            CurrentPower = 41m,
                            Name = "Adam Warlock",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7104),
                            StartingPower = 41m
                        },
                        new
                        {
                            Id = new Guid("f12d6c3a-cdd5-4dd4-ab71-daeb74163107"),
                            Ability = "Attacker",
                            ApplicationUserId = "62029255-19a6-4583-bb55-1bd251999ff1",
                            CurrentPower = 39m,
                            Name = "Loki",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7118),
                            StartingPower = 39m
                        },
                        new
                        {
                            Id = new Guid("588f56a9-88d1-427e-a402-28a32f4d40b0"),
                            Ability = "Attacker",
                            ApplicationUserId = "62029255-19a6-4583-bb55-1bd251999ff1",
                            CurrentPower = 38m,
                            Name = "Hela",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7128),
                            StartingPower = 38m
                        },
                        new
                        {
                            Id = new Guid("a1f86a62-c15f-408a-b4fa-5336d86c779f"),
                            Ability = "Attacker",
                            ApplicationUserId = "62029255-19a6-4583-bb55-1bd251999ff1",
                            CurrentPower = 42m,
                            Name = "She-Hulk",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7138),
                            StartingPower = 42m
                        },
                        new
                        {
                            Id = new Guid("25bf2b6c-f2c5-4714-93ac-1be15374bca2"),
                            Ability = "Attacker",
                            ApplicationUserId = "62029255-19a6-4583-bb55-1bd251999ff1",
                            CurrentPower = 46m,
                            Name = "Dr. Doom",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7146),
                            StartingPower = 46m
                        },
                        new
                        {
                            Id = new Guid("1e6b4e3d-db3e-43b6-ab64-7edbec2cb6d3"),
                            Ability = "Defender",
                            ApplicationUserId = "62029255-19a6-4583-bb55-1bd251999ff1",
                            CurrentPower = 30m,
                            Name = "Bat-Girl",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7154),
                            StartingPower = 30m
                        },
                        new
                        {
                            Id = new Guid("0aaf71ff-372e-4b91-ae1a-386d87824051"),
                            Ability = "Attacker",
                            ApplicationUserId = "62029255-19a6-4583-bb55-1bd251999ff1",
                            CurrentPower = 46m,
                            Name = "Super-Girl",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 19, 6, 26, 152, DateTimeKind.Utc).AddTicks(7163),
                            StartingPower = 46m
                        });
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroSuitColor", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HeroId", "ColorName");

                    b.ToTable("HeroSuitColors");

                    b.HasData(
                        new
                        {
                            HeroId = new Guid("8fd13349-ee75-43b8-9c34-999cbafc2d8a"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("8fd13349-ee75-43b8-9c34-999cbafc2d8a"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("a4c95cf6-33db-4db9-b108-de76a0b5dce1"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("a4c95cf6-33db-4db9-b108-de76a0b5dce1"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("9e349f66-9bd8-4ce4-bcd4-21213ce71dc6"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("9e349f66-9bd8-4ce4-bcd4-21213ce71dc6"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("6d7819ca-efda-478e-ab81-0a545f4cc1e2"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("6d7819ca-efda-478e-ab81-0a545f4cc1e2"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("5731ae4e-fa73-47d9-8c20-9553d4b582ff"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("5731ae4e-fa73-47d9-8c20-9553d4b582ff"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("3a10bf79-85dd-4703-ab45-4f3ca23f4518"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("3a10bf79-85dd-4703-ab45-4f3ca23f4518"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("a249ce29-a842-469e-bea6-63fc400d5897"),
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HeroId = new Guid("a249ce29-a842-469e-bea6-63fc400d5897"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("b4731181-eaf0-4c25-a0fb-e346979f8b13"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("b4731181-eaf0-4c25-a0fb-e346979f8b13"),
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HeroId = new Guid("9ca081c2-2be9-491b-9db0-973005b505a8"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("9ca081c2-2be9-491b-9db0-973005b505a8"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("5956738d-c40c-4995-bb5a-c69809b58f48"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("5956738d-c40c-4995-bb5a-c69809b58f48"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("4fb8ecbf-d8e7-427d-b80e-c330bc718ad4"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("4fb8ecbf-d8e7-427d-b80e-c330bc718ad4"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("7140ca1f-ccce-42e3-aa5a-1df93e347c9c"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("7140ca1f-ccce-42e3-aa5a-1df93e347c9c"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("e9c119f5-7cba-4c32-9326-478fccd7d90d"),
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HeroId = new Guid("e9c119f5-7cba-4c32-9326-478fccd7d90d"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("0631cff2-cbc8-4be7-a518-422b395183fc"),
                            ColorName = "Purple"
                        },
                        new
                        {
                            HeroId = new Guid("0631cff2-cbc8-4be7-a518-422b395183fc"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("4bd00c16-d738-4acd-8c95-6e04483061d5"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("4bd00c16-d738-4acd-8c95-6e04483061d5"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("7297dc26-0268-4d58-af2e-3048e11fb473"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("7297dc26-0268-4d58-af2e-3048e11fb473"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("9d61dd61-bf35-486a-9c47-3d6c849985b8"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("9d61dd61-bf35-486a-9c47-3d6c849985b8"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("e4838b46-c1f6-4c77-be4e-de7fe01675e6"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("e4838b46-c1f6-4c77-be4e-de7fe01675e6"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("9be7d241-b13b-4f2f-b565-9de69329a63a"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("9be7d241-b13b-4f2f-b565-9de69329a63a"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("1d5e4f75-7a5e-477d-9487-353074933703"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("1d5e4f75-7a5e-477d-9487-353074933703"),
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HeroId = new Guid("4c939e82-0569-427d-8e86-776406cd0416"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("4c939e82-0569-427d-8e86-776406cd0416"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("6f8cdcfb-3378-49e2-b5c5-58768294f7b2"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("6f8cdcfb-3378-49e2-b5c5-58768294f7b2"),
                            ColorName = "Purple"
                        },
                        new
                        {
                            HeroId = new Guid("34ac0bad-c01c-4b28-bb38-baa351aabd93"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("34ac0bad-c01c-4b28-bb38-baa351aabd93"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("071c7a42-11f8-4438-b737-b9bc6b04c989"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("071c7a42-11f8-4438-b737-b9bc6b04c989"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("f12d6c3a-cdd5-4dd4-ab71-daeb74163107"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("f12d6c3a-cdd5-4dd4-ab71-daeb74163107"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("588f56a9-88d1-427e-a402-28a32f4d40b0"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("588f56a9-88d1-427e-a402-28a32f4d40b0"),
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HeroId = new Guid("a1f86a62-c15f-408a-b4fa-5336d86c779f"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("a1f86a62-c15f-408a-b4fa-5336d86c779f"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("25bf2b6c-f2c5-4714-93ac-1be15374bca2"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("25bf2b6c-f2c5-4714-93ac-1be15374bca2"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("1e6b4e3d-db3e-43b6-ab64-7edbec2cb6d3"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("1e6b4e3d-db3e-43b6-ab64-7edbec2cb6d3"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("0aaf71ff-372e-4b91-ae1a-386d87824051"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("0aaf71ff-372e-4b91-ae1a-386d87824051"),
                            ColorName = "Red"
                        });
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroTraining", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HeroId", "TrainedAt");

                    b.ToTable("HeroTrainings");
                });

            modelBuilder.Entity("HeroesApi.Models.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "56522a96-07e6-4331-afea-b3c4fedc4039",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ecc3c1d7-ec73-4857-9140-8152db39c500",
                            Email = "user1@example.com",
                            EmailConfirmed = false,
                            FirstName = "Moshe",
                            LastName = "Cohen",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEKIm0nYdxOWeMPfZrY4z1L4gVB/pjYrab3fi7CTiwF4m8E+Pk/DqzzhU4GHVAJ+eUw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c395dd87-1e16-4bd7-935a-0fa3b6e45371",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = "49ba864d-5963-493f-8254-217192dfe74b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a3759961-35a4-4745-b1c8-d9d2649a2cd5",
                            Email = "user2@example.com",
                            EmailConfirmed = false,
                            FirstName = "Keren",
                            LastName = "David",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEG8bio9iY8zwHhNzjwAzY+vlCU52solJRUU22kigc2vYJxzY/WguAPBTSfQIiXhZZg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f3556fcb-89d2-4a31-884f-73b8ace71e7f",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        },
                        new
                        {
                            Id = "62029255-19a6-4583-bb55-1bd251999ff1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9cde9ff2-6abb-47f9-a60c-113b12df6e8e",
                            Email = "user3@example.com",
                            EmailConfirmed = false,
                            FirstName = "Sholomo",
                            LastName = "Daniel",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEK0e72uqRORaVFCW+Z2+jITS6C0XKMrz7BKh15tpoqs2fb/0L2A3r0YlT1EYMrhe3g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e9f7105c-5a5b-4735-a149-4062f18f1d15",
                            TwoFactorEnabled = false,
                            UserName = "user3@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.Hero", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany("Heroes")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroSuitColor", b =>
                {
                    b.HasOne("HeroesApi.Models.Heroes.Hero", null)
                        .WithMany("SuitColors")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroTraining", b =>
                {
                    b.HasOne("HeroesApi.Models.Heroes.Hero", null)
                        .WithMany("HeroTrainings")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.Hero", b =>
                {
                    b.Navigation("HeroTrainings");

                    b.Navigation("SuitColors");
                });

            modelBuilder.Entity("HeroesApi.Models.IdentityModels.ApplicationUser", b =>
                {
                    b.Navigation("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
