// <auto-generated />
using System;
using HeroesApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroesApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220308203110_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HeroesApi.Models.Heroes.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CurrentPower")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartedTrainingAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartingPower")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e23f4c6b-728e-43e5-b210-4b7cbc5363c6"),
                            Ability = "Defender",
                            ApplicationUserId = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            CurrentPower = 41m,
                            Name = "Dr. Strange",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6621),
                            StartingPower = 41m
                        },
                        new
                        {
                            Id = new Guid("6035bd5b-bbf3-4264-b047-e1b8ec7d634d"),
                            Ability = "Defender",
                            ApplicationUserId = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            CurrentPower = 31m,
                            Name = "Deadpool",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6633),
                            StartingPower = 31m
                        },
                        new
                        {
                            Id = new Guid("6a9750a5-75b9-41e0-a905-8321cee7c6af"),
                            Ability = "Attacker",
                            ApplicationUserId = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            CurrentPower = 42m,
                            Name = "Thanos",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6645),
                            StartingPower = 42m
                        },
                        new
                        {
                            Id = new Guid("208ad836-e216-45f0-8501-2e53f5286d2e"),
                            Ability = "Attacker",
                            ApplicationUserId = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            CurrentPower = 32m,
                            Name = "Iron-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6656),
                            StartingPower = 32m
                        },
                        new
                        {
                            Id = new Guid("215ba930-e057-43fa-aa0d-b83cc664eaa2"),
                            Ability = "Attacker",
                            ApplicationUserId = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            CurrentPower = 41m,
                            Name = "Captain America",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6666),
                            StartingPower = 41m
                        },
                        new
                        {
                            Id = new Guid("cdaf7f80-4d22-4e01-8640-7a2c4358a17c"),
                            Ability = "Defender",
                            ApplicationUserId = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            CurrentPower = 38m,
                            Name = "Thor",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6675),
                            StartingPower = 38m
                        },
                        new
                        {
                            Id = new Guid("0a3e8b52-e3be-4816-a61f-641b277ebab2"),
                            Ability = "Defender",
                            ApplicationUserId = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            CurrentPower = 41m,
                            Name = "Black Widow",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6683),
                            StartingPower = 41m
                        },
                        new
                        {
                            Id = new Guid("19b1f271-6042-4a10-9ad8-d42f0c63964c"),
                            Ability = "Attacker",
                            ApplicationUserId = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            CurrentPower = 38m,
                            Name = "Scarlet Witch",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6745),
                            StartingPower = 38m
                        },
                        new
                        {
                            Id = new Guid("93ac9611-f4af-4d50-91ae-23d49365af55"),
                            Ability = "Attacker",
                            ApplicationUserId = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            CurrentPower = 35m,
                            Name = "Captain Marvel",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6757),
                            StartingPower = 35m
                        },
                        new
                        {
                            Id = new Guid("006efc8c-c0e0-4faa-88a4-3e12f43f5398"),
                            Ability = "Defender",
                            ApplicationUserId = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            CurrentPower = 43m,
                            Name = "Pheonix",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6765),
                            StartingPower = 43m
                        },
                        new
                        {
                            Id = new Guid("d288a1e5-5f2e-4c97-a399-4ce2c98c97f6"),
                            Ability = "Attacker",
                            ApplicationUserId = "f2283146-4b61-491e-8002-c361c52d9082",
                            CurrentPower = 40m,
                            Name = "Spider-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6775),
                            StartingPower = 40m
                        },
                        new
                        {
                            Id = new Guid("864d40d2-95e8-4f9d-b563-59a0b980c812"),
                            Ability = "Attacker",
                            ApplicationUserId = "f2283146-4b61-491e-8002-c361c52d9082",
                            CurrentPower = 34m,
                            Name = "The Punisher",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6782),
                            StartingPower = 34m
                        },
                        new
                        {
                            Id = new Guid("519ced22-4303-473d-8293-68308b8e6ee4"),
                            Ability = "Attacker",
                            ApplicationUserId = "f2283146-4b61-491e-8002-c361c52d9082",
                            CurrentPower = 50m,
                            Name = "The Hulk",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6790),
                            StartingPower = 50m
                        },
                        new
                        {
                            Id = new Guid("017d95a3-4e67-4d07-b677-2e8250e3f7be"),
                            Ability = "Defender",
                            ApplicationUserId = "f2283146-4b61-491e-8002-c361c52d9082",
                            CurrentPower = 39m,
                            Name = "Wolverine",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6801),
                            StartingPower = 39m
                        },
                        new
                        {
                            Id = new Guid("e6799233-35dd-4249-a9b6-e76303df2326"),
                            Ability = "Defender",
                            ApplicationUserId = "f2283146-4b61-491e-8002-c361c52d9082",
                            CurrentPower = 34m,
                            Name = "Ant-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6809),
                            StartingPower = 34m
                        },
                        new
                        {
                            Id = new Guid("108bddb1-a4eb-4fe8-835d-beb4706c81be"),
                            Ability = "Defender",
                            ApplicationUserId = "f2283146-4b61-491e-8002-c361c52d9082",
                            CurrentPower = 45m,
                            Name = "Black Panther",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6817),
                            StartingPower = 45m
                        },
                        new
                        {
                            Id = new Guid("6a724f99-c2a9-42da-959f-77ad500df838"),
                            Ability = "Attacker",
                            ApplicationUserId = "f2283146-4b61-491e-8002-c361c52d9082",
                            CurrentPower = 40m,
                            Name = "Venom",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6827),
                            StartingPower = 40m
                        },
                        new
                        {
                            Id = new Guid("8d938c90-0099-42a7-add2-fa6fd7cf9003"),
                            Ability = "Attacker",
                            ApplicationUserId = "f2283146-4b61-491e-8002-c361c52d9082",
                            CurrentPower = 43m,
                            Name = "Star Lord",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6835),
                            StartingPower = 43m
                        },
                        new
                        {
                            Id = new Guid("36ca83e9-054c-4db2-a7e5-5eb827292ca3"),
                            Ability = "Attacker",
                            ApplicationUserId = "f2283146-4b61-491e-8002-c361c52d9082",
                            CurrentPower = 37m,
                            Name = "Super-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6843),
                            StartingPower = 37m
                        },
                        new
                        {
                            Id = new Guid("ba235dcc-c254-4bc0-911f-fb3b5c0ab087"),
                            Ability = "Attacker",
                            ApplicationUserId = "f2283146-4b61-491e-8002-c361c52d9082",
                            CurrentPower = 34m,
                            Name = "Bat-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6850),
                            StartingPower = 34m
                        },
                        new
                        {
                            Id = new Guid("b01be38a-fd61-46ec-931f-cf4de535c4cf"),
                            Ability = "Attacker",
                            ApplicationUserId = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            CurrentPower = 42m,
                            Name = "The Joker",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6890),
                            StartingPower = 42m
                        },
                        new
                        {
                            Id = new Guid("132ea55f-5b82-422c-82a1-4ed58b00d98f"),
                            Ability = "Defender",
                            ApplicationUserId = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            CurrentPower = 47m,
                            Name = "Bane",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6898),
                            StartingPower = 47m
                        },
                        new
                        {
                            Id = new Guid("93530afb-f394-4057-9932-acd69f3eb487"),
                            Ability = "Defender",
                            ApplicationUserId = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            CurrentPower = 50m,
                            Name = "Wonder Woman",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6906),
                            StartingPower = 50m
                        },
                        new
                        {
                            Id = new Guid("b4efd809-e821-4d42-85f7-1c85238f3198"),
                            Ability = "Defender",
                            ApplicationUserId = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            CurrentPower = 43m,
                            Name = "Adam Warlock",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6914),
                            StartingPower = 43m
                        },
                        new
                        {
                            Id = new Guid("7598f1ef-c840-4251-8de6-52c7b9fac206"),
                            Ability = "Defender",
                            ApplicationUserId = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            CurrentPower = 32m,
                            Name = "Loki",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6922),
                            StartingPower = 32m
                        },
                        new
                        {
                            Id = new Guid("897209e9-a2b2-4890-bb73-12f6f7392ff9"),
                            Ability = "Attacker",
                            ApplicationUserId = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            CurrentPower = 50m,
                            Name = "Hela",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6930),
                            StartingPower = 50m
                        },
                        new
                        {
                            Id = new Guid("c891de5d-b0a0-4e3a-8cce-f1a03d586966"),
                            Ability = "Defender",
                            ApplicationUserId = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            CurrentPower = 35m,
                            Name = "She-Hulk",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6939),
                            StartingPower = 35m
                        },
                        new
                        {
                            Id = new Guid("5b57b2ec-8ad8-4790-9038-50c14c795530"),
                            Ability = "Defender",
                            ApplicationUserId = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            CurrentPower = 33m,
                            Name = "Dr. Doom",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6947),
                            StartingPower = 33m
                        },
                        new
                        {
                            Id = new Guid("1eba75e9-de78-4143-a309-e351c36d7a38"),
                            Ability = "Defender",
                            ApplicationUserId = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            CurrentPower = 50m,
                            Name = "Bat-Girl",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6957),
                            StartingPower = 50m
                        },
                        new
                        {
                            Id = new Guid("dd95a3f3-3568-444e-b300-3491eedf9758"),
                            Ability = "Defender",
                            ApplicationUserId = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            CurrentPower = 37m,
                            Name = "Super-Girl",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 31, 10, 398, DateTimeKind.Utc).AddTicks(6965),
                            StartingPower = 37m
                        });
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroSuitColor", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HeroId", "ColorName");

                    b.ToTable("HeroSuitColors");

                    b.HasData(
                        new
                        {
                            HeroId = new Guid("e23f4c6b-728e-43e5-b210-4b7cbc5363c6"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("e23f4c6b-728e-43e5-b210-4b7cbc5363c6"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("6035bd5b-bbf3-4264-b047-e1b8ec7d634d"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("6035bd5b-bbf3-4264-b047-e1b8ec7d634d"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("6a9750a5-75b9-41e0-a905-8321cee7c6af"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("6a9750a5-75b9-41e0-a905-8321cee7c6af"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("208ad836-e216-45f0-8501-2e53f5286d2e"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("208ad836-e216-45f0-8501-2e53f5286d2e"),
                            ColorName = "Purple"
                        },
                        new
                        {
                            HeroId = new Guid("215ba930-e057-43fa-aa0d-b83cc664eaa2"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("215ba930-e057-43fa-aa0d-b83cc664eaa2"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("cdaf7f80-4d22-4e01-8640-7a2c4358a17c"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("cdaf7f80-4d22-4e01-8640-7a2c4358a17c"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("0a3e8b52-e3be-4816-a61f-641b277ebab2"),
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HeroId = new Guid("0a3e8b52-e3be-4816-a61f-641b277ebab2"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("19b1f271-6042-4a10-9ad8-d42f0c63964c"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("19b1f271-6042-4a10-9ad8-d42f0c63964c"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("93ac9611-f4af-4d50-91ae-23d49365af55"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("93ac9611-f4af-4d50-91ae-23d49365af55"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("006efc8c-c0e0-4faa-88a4-3e12f43f5398"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("006efc8c-c0e0-4faa-88a4-3e12f43f5398"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("d288a1e5-5f2e-4c97-a399-4ce2c98c97f6"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("d288a1e5-5f2e-4c97-a399-4ce2c98c97f6"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("864d40d2-95e8-4f9d-b563-59a0b980c812"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("864d40d2-95e8-4f9d-b563-59a0b980c812"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("519ced22-4303-473d-8293-68308b8e6ee4"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("519ced22-4303-473d-8293-68308b8e6ee4"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("017d95a3-4e67-4d07-b677-2e8250e3f7be"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("017d95a3-4e67-4d07-b677-2e8250e3f7be"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("e6799233-35dd-4249-a9b6-e76303df2326"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("e6799233-35dd-4249-a9b6-e76303df2326"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("108bddb1-a4eb-4fe8-835d-beb4706c81be"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("108bddb1-a4eb-4fe8-835d-beb4706c81be"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("6a724f99-c2a9-42da-959f-77ad500df838"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("6a724f99-c2a9-42da-959f-77ad500df838"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("8d938c90-0099-42a7-add2-fa6fd7cf9003"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("8d938c90-0099-42a7-add2-fa6fd7cf9003"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("36ca83e9-054c-4db2-a7e5-5eb827292ca3"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("36ca83e9-054c-4db2-a7e5-5eb827292ca3"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("ba235dcc-c254-4bc0-911f-fb3b5c0ab087"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("ba235dcc-c254-4bc0-911f-fb3b5c0ab087"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("b01be38a-fd61-46ec-931f-cf4de535c4cf"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("b01be38a-fd61-46ec-931f-cf4de535c4cf"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("132ea55f-5b82-422c-82a1-4ed58b00d98f"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("132ea55f-5b82-422c-82a1-4ed58b00d98f"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("93530afb-f394-4057-9932-acd69f3eb487"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("93530afb-f394-4057-9932-acd69f3eb487"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("b4efd809-e821-4d42-85f7-1c85238f3198"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("b4efd809-e821-4d42-85f7-1c85238f3198"),
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HeroId = new Guid("7598f1ef-c840-4251-8de6-52c7b9fac206"),
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HeroId = new Guid("7598f1ef-c840-4251-8de6-52c7b9fac206"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("897209e9-a2b2-4890-bb73-12f6f7392ff9"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("897209e9-a2b2-4890-bb73-12f6f7392ff9"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("c891de5d-b0a0-4e3a-8cce-f1a03d586966"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("c891de5d-b0a0-4e3a-8cce-f1a03d586966"),
                            ColorName = "Purple"
                        },
                        new
                        {
                            HeroId = new Guid("5b57b2ec-8ad8-4790-9038-50c14c795530"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("5b57b2ec-8ad8-4790-9038-50c14c795530"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("1eba75e9-de78-4143-a309-e351c36d7a38"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("1eba75e9-de78-4143-a309-e351c36d7a38"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("dd95a3f3-3568-444e-b300-3491eedf9758"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("dd95a3f3-3568-444e-b300-3491eedf9758"),
                            ColorName = "Black"
                        });
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroTraining", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HeroId", "TrainedAt");

                    b.ToTable("HeroTrainings");
                });

            modelBuilder.Entity("HeroesApi.Models.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "690f8f27-48ce-439c-b9d8-d7905ae16028",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "abaffbcc-2fec-4801-97e2-f473d12a14d6",
                            Email = "user1@example.com",
                            EmailConfirmed = false,
                            FirstName = "Moshe",
                            LastName = "Cohen",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEINEQLCPRroTwxTYIL0YJoxpaGMnTZUHWMfqvnQDbwRMbWGrzkSMueGRD9TbwDAgxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "447bc8f5-75f9-4117-be3e-27f858358480",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = "f2283146-4b61-491e-8002-c361c52d9082",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c00f76b8-5a94-444c-a323-b99e5450c6da",
                            Email = "user2@example.com",
                            EmailConfirmed = false,
                            FirstName = "Keren",
                            LastName = "David",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIXUMnD0Zn3yv7SBJe6q2G4JaL7PtHfiRx0xRK6uJXIQ4LxJsE8ayz9dNVwgV1Z9pQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "de7a32fe-597f-47b0-97d2-cee361639adb",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        },
                        new
                        {
                            Id = "aaf0d392-1d51-4bc8-a308-58fe3376497d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2698ecd-f700-44d6-ab1b-4c2a46d12813",
                            Email = "user3@example.com",
                            EmailConfirmed = false,
                            FirstName = "Sholomo",
                            LastName = "Daniel",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER3@EXAMPLE.COM",
                            NormalizedUserName = "USER3@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMOrwUYqqVYD+n4Nk2KK68jiPLulPX5urPuZ1WELClB7qSxkn9ydOI9Xai10wc9gMA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c457909e-ecc6-4ce0-b22b-74be7ae2600f",
                            TwoFactorEnabled = false,
                            UserName = "user3@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.Hero", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany("Heroes")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroSuitColor", b =>
                {
                    b.HasOne("HeroesApi.Models.Heroes.Hero", null)
                        .WithMany("SuitColors")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroTraining", b =>
                {
                    b.HasOne("HeroesApi.Models.Heroes.Hero", null)
                        .WithMany("HeroTrainings")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.Hero", b =>
                {
                    b.Navigation("HeroTrainings");

                    b.Navigation("SuitColors");
                });

            modelBuilder.Entity("HeroesApi.Models.IdentityModels.ApplicationUser", b =>
                {
                    b.Navigation("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
