// <auto-generated />
using System;
using HeroesApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroesApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HeroesApi.Models.Heroes.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CurrentPower")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartedTrainingAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartingPower")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f9f1c5b-a8f6-4f3c-bda9-b526db09bf65"),
                            Ability = "Attacker",
                            ApplicationUserId = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            CurrentPower = 40m,
                            Name = "Dr. Strange",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8723),
                            StartingPower = 40m
                        },
                        new
                        {
                            Id = new Guid("fce6821a-9198-4e86-bf05-e718f5afd204"),
                            Ability = "Defender",
                            ApplicationUserId = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            CurrentPower = 38m,
                            Name = "Deadpool",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8734),
                            StartingPower = 38m
                        },
                        new
                        {
                            Id = new Guid("6a4a57ce-dcf2-4fc8-a910-eb7d63c674f7"),
                            Ability = "Attacker",
                            ApplicationUserId = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            CurrentPower = 47m,
                            Name = "Thanos",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8744),
                            StartingPower = 47m
                        },
                        new
                        {
                            Id = new Guid("519e5d81-f984-4dce-b3dd-f234ecf8f7a6"),
                            Ability = "Defender",
                            ApplicationUserId = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            CurrentPower = 40m,
                            Name = "Iron-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8754),
                            StartingPower = 40m
                        },
                        new
                        {
                            Id = new Guid("4fc3a829-b9c4-4c40-8ea4-6a4556731657"),
                            Ability = "Defender",
                            ApplicationUserId = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            CurrentPower = 45m,
                            Name = "Captain America",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8763),
                            StartingPower = 45m
                        },
                        new
                        {
                            Id = new Guid("6bf34c4c-bc58-48cc-a88b-77c054a5f16d"),
                            Ability = "Defender",
                            ApplicationUserId = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            CurrentPower = 30m,
                            Name = "Thor",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8773),
                            StartingPower = 30m
                        },
                        new
                        {
                            Id = new Guid("0515d54c-6203-401b-8688-215eabe8c97e"),
                            Ability = "Defender",
                            ApplicationUserId = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            CurrentPower = 41m,
                            Name = "Black Widow",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8819),
                            StartingPower = 41m
                        },
                        new
                        {
                            Id = new Guid("162ec52a-7fa0-4479-9743-313fb078bfd5"),
                            Ability = "Attacker",
                            ApplicationUserId = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            CurrentPower = 35m,
                            Name = "Scarlet Witch",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8828),
                            StartingPower = 35m
                        },
                        new
                        {
                            Id = new Guid("e77f19b9-960d-4e8d-aac7-f4fc84c75d7c"),
                            Ability = "Defender",
                            ApplicationUserId = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            CurrentPower = 35m,
                            Name = "Captain Marvel",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8837),
                            StartingPower = 35m
                        },
                        new
                        {
                            Id = new Guid("72d05fb9-9a9a-4679-85e5-6947a42a7237"),
                            Ability = "Defender",
                            ApplicationUserId = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            CurrentPower = 32m,
                            Name = "Pheonix",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8848),
                            StartingPower = 32m
                        },
                        new
                        {
                            Id = new Guid("5971e187-2092-4e7e-b41f-5088d90b4b5a"),
                            Ability = "Attacker",
                            ApplicationUserId = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            CurrentPower = 44m,
                            Name = "Spider-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8857),
                            StartingPower = 44m
                        },
                        new
                        {
                            Id = new Guid("16c4ae8c-7ac0-44b4-a14c-3702bb9cef26"),
                            Ability = "Defender",
                            ApplicationUserId = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            CurrentPower = 43m,
                            Name = "The Punisher",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8864),
                            StartingPower = 43m
                        },
                        new
                        {
                            Id = new Guid("4a1315b3-5b82-4ff5-8d5c-78376274a024"),
                            Ability = "Attacker",
                            ApplicationUserId = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            CurrentPower = 46m,
                            Name = "The Hulk",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8872),
                            StartingPower = 46m
                        },
                        new
                        {
                            Id = new Guid("9e38dcaf-6f3d-425f-af2b-9dde72d3d684"),
                            Ability = "Attacker",
                            ApplicationUserId = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            CurrentPower = 45m,
                            Name = "Wolverine",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8879),
                            StartingPower = 45m
                        },
                        new
                        {
                            Id = new Guid("b33596a1-d057-45db-8d05-351b709a3dd8"),
                            Ability = "Attacker",
                            ApplicationUserId = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            CurrentPower = 50m,
                            Name = "Ant-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8887),
                            StartingPower = 50m
                        },
                        new
                        {
                            Id = new Guid("cf1d1642-d725-47a1-bcf9-8101f6ee4606"),
                            Ability = "Defender",
                            ApplicationUserId = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            CurrentPower = 33m,
                            Name = "Black Panther",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8897),
                            StartingPower = 33m
                        },
                        new
                        {
                            Id = new Guid("f1500394-f6e9-48ec-8966-f02129a6f736"),
                            Ability = "Defender",
                            ApplicationUserId = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            CurrentPower = 36m,
                            Name = "Venom",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8905),
                            StartingPower = 36m
                        },
                        new
                        {
                            Id = new Guid("26f81fbd-3de8-4a95-aabf-4d555230e1ee"),
                            Ability = "Defender",
                            ApplicationUserId = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            CurrentPower = 30m,
                            Name = "Star Lord",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8914),
                            StartingPower = 30m
                        },
                        new
                        {
                            Id = new Guid("9d09fe7c-5efa-4100-ab4c-825a9ae058a9"),
                            Ability = "Defender",
                            ApplicationUserId = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            CurrentPower = 48m,
                            Name = "Super-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8921),
                            StartingPower = 48m
                        },
                        new
                        {
                            Id = new Guid("583b8c19-d2f4-4b5a-a5c3-4237a43e19a8"),
                            Ability = "Attacker",
                            ApplicationUserId = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            CurrentPower = 35m,
                            Name = "Bat-Man",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8958),
                            StartingPower = 35m
                        },
                        new
                        {
                            Id = new Guid("c74ea23f-8d15-43e8-bee5-0eafa8e176d2"),
                            Ability = "Attacker",
                            ApplicationUserId = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            CurrentPower = 42m,
                            Name = "The Joker",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8967),
                            StartingPower = 42m
                        },
                        new
                        {
                            Id = new Guid("0b4d29d1-b3e4-4872-8f50-8c57b0de7f15"),
                            Ability = "Attacker",
                            ApplicationUserId = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            CurrentPower = 35m,
                            Name = "Bane",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8975),
                            StartingPower = 35m
                        },
                        new
                        {
                            Id = new Guid("fac2a098-7438-4778-819d-7109d81abacd"),
                            Ability = "Defender",
                            ApplicationUserId = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            CurrentPower = 36m,
                            Name = "Wonder Woman",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8982),
                            StartingPower = 36m
                        },
                        new
                        {
                            Id = new Guid("5b6c9bc5-0e1d-41b6-99c4-4ba6f6c6f22f"),
                            Ability = "Attacker",
                            ApplicationUserId = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            CurrentPower = 50m,
                            Name = "Adam Warlock",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8991),
                            StartingPower = 50m
                        },
                        new
                        {
                            Id = new Guid("c690b45c-93a6-43f5-972b-e2c242fc011e"),
                            Ability = "Attacker",
                            ApplicationUserId = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            CurrentPower = 40m,
                            Name = "Loki",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(8999),
                            StartingPower = 40m
                        },
                        new
                        {
                            Id = new Guid("364e91be-f233-4690-877a-7a0382f703cf"),
                            Ability = "Defender",
                            ApplicationUserId = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            CurrentPower = 33m,
                            Name = "Hela",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(9006),
                            StartingPower = 33m
                        },
                        new
                        {
                            Id = new Guid("511a0da2-f6db-4cce-8c70-71a36bd61748"),
                            Ability = "Attacker",
                            ApplicationUserId = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            CurrentPower = 43m,
                            Name = "She-Hulk",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(9013),
                            StartingPower = 43m
                        },
                        new
                        {
                            Id = new Guid("6b6f40bd-67c9-43f7-91ed-745c0bea01c6"),
                            Ability = "Defender",
                            ApplicationUserId = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            CurrentPower = 45m,
                            Name = "Dr. Doom",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(9021),
                            StartingPower = 45m
                        },
                        new
                        {
                            Id = new Guid("ed35fa6a-8763-45ed-8579-9907c5c6a0a0"),
                            Ability = "Defender",
                            ApplicationUserId = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            CurrentPower = 40m,
                            Name = "Bat-Girl",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(9028),
                            StartingPower = 40m
                        },
                        new
                        {
                            Id = new Guid("17cca59e-e2d7-4f53-ae8d-952297151463"),
                            Ability = "Defender",
                            ApplicationUserId = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            CurrentPower = 50m,
                            Name = "Super-Girl",
                            StartedTrainingAt = new DateTime(2022, 3, 8, 20, 11, 35, 312, DateTimeKind.Utc).AddTicks(9035),
                            StartingPower = 50m
                        });
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroSuitColor", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HeroId", "ColorName");

                    b.ToTable("HeroSuitColors");

                    b.HasData(
                        new
                        {
                            HeroId = new Guid("1f9f1c5b-a8f6-4f3c-bda9-b526db09bf65"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("1f9f1c5b-a8f6-4f3c-bda9-b526db09bf65"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("fce6821a-9198-4e86-bf05-e718f5afd204"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("fce6821a-9198-4e86-bf05-e718f5afd204"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("6a4a57ce-dcf2-4fc8-a910-eb7d63c674f7"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("6a4a57ce-dcf2-4fc8-a910-eb7d63c674f7"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("519e5d81-f984-4dce-b3dd-f234ecf8f7a6"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("519e5d81-f984-4dce-b3dd-f234ecf8f7a6"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("4fc3a829-b9c4-4c40-8ea4-6a4556731657"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("4fc3a829-b9c4-4c40-8ea4-6a4556731657"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("6bf34c4c-bc58-48cc-a88b-77c054a5f16d"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("6bf34c4c-bc58-48cc-a88b-77c054a5f16d"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("0515d54c-6203-401b-8688-215eabe8c97e"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("0515d54c-6203-401b-8688-215eabe8c97e"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("162ec52a-7fa0-4479-9743-313fb078bfd5"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("162ec52a-7fa0-4479-9743-313fb078bfd5"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("e77f19b9-960d-4e8d-aac7-f4fc84c75d7c"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("e77f19b9-960d-4e8d-aac7-f4fc84c75d7c"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("72d05fb9-9a9a-4679-85e5-6947a42a7237"),
                            ColorName = "Purple"
                        },
                        new
                        {
                            HeroId = new Guid("72d05fb9-9a9a-4679-85e5-6947a42a7237"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("5971e187-2092-4e7e-b41f-5088d90b4b5a"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("5971e187-2092-4e7e-b41f-5088d90b4b5a"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("16c4ae8c-7ac0-44b4-a14c-3702bb9cef26"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("16c4ae8c-7ac0-44b4-a14c-3702bb9cef26"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("4a1315b3-5b82-4ff5-8d5c-78376274a024"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("4a1315b3-5b82-4ff5-8d5c-78376274a024"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("9e38dcaf-6f3d-425f-af2b-9dde72d3d684"),
                            ColorName = "Purple"
                        },
                        new
                        {
                            HeroId = new Guid("9e38dcaf-6f3d-425f-af2b-9dde72d3d684"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("b33596a1-d057-45db-8d05-351b709a3dd8"),
                            ColorName = "Gold"
                        },
                        new
                        {
                            HeroId = new Guid("b33596a1-d057-45db-8d05-351b709a3dd8"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("cf1d1642-d725-47a1-bcf9-8101f6ee4606"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("cf1d1642-d725-47a1-bcf9-8101f6ee4606"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("f1500394-f6e9-48ec-8966-f02129a6f736"),
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HeroId = new Guid("f1500394-f6e9-48ec-8966-f02129a6f736"),
                            ColorName = "Purple"
                        },
                        new
                        {
                            HeroId = new Guid("26f81fbd-3de8-4a95-aabf-4d555230e1ee"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("26f81fbd-3de8-4a95-aabf-4d555230e1ee"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("9d09fe7c-5efa-4100-ab4c-825a9ae058a9"),
                            ColorName = "Black"
                        },
                        new
                        {
                            HeroId = new Guid("9d09fe7c-5efa-4100-ab4c-825a9ae058a9"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("583b8c19-d2f4-4b5a-a5c3-4237a43e19a8"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("583b8c19-d2f4-4b5a-a5c3-4237a43e19a8"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("c74ea23f-8d15-43e8-bee5-0eafa8e176d2"),
                            ColorName = "Purple"
                        },
                        new
                        {
                            HeroId = new Guid("c74ea23f-8d15-43e8-bee5-0eafa8e176d2"),
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HeroId = new Guid("0b4d29d1-b3e4-4872-8f50-8c57b0de7f15"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("0b4d29d1-b3e4-4872-8f50-8c57b0de7f15"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("fac2a098-7438-4778-819d-7109d81abacd"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("fac2a098-7438-4778-819d-7109d81abacd"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("5b6c9bc5-0e1d-41b6-99c4-4ba6f6c6f22f"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("5b6c9bc5-0e1d-41b6-99c4-4ba6f6c6f22f"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("c690b45c-93a6-43f5-972b-e2c242fc011e"),
                            ColorName = "Green"
                        },
                        new
                        {
                            HeroId = new Guid("c690b45c-93a6-43f5-972b-e2c242fc011e"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("364e91be-f233-4690-877a-7a0382f703cf"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("364e91be-f233-4690-877a-7a0382f703cf"),
                            ColorName = "Red"
                        },
                        new
                        {
                            HeroId = new Guid("511a0da2-f6db-4cce-8c70-71a36bd61748"),
                            ColorName = "White"
                        },
                        new
                        {
                            HeroId = new Guid("511a0da2-f6db-4cce-8c70-71a36bd61748"),
                            ColorName = "Orange"
                        },
                        new
                        {
                            HeroId = new Guid("6b6f40bd-67c9-43f7-91ed-745c0bea01c6"),
                            ColorName = "Silver"
                        },
                        new
                        {
                            HeroId = new Guid("6b6f40bd-67c9-43f7-91ed-745c0bea01c6"),
                            ColorName = "Purple"
                        },
                        new
                        {
                            HeroId = new Guid("ed35fa6a-8763-45ed-8579-9907c5c6a0a0"),
                            ColorName = "Pink"
                        },
                        new
                        {
                            HeroId = new Guid("ed35fa6a-8763-45ed-8579-9907c5c6a0a0"),
                            ColorName = "Blue"
                        },
                        new
                        {
                            HeroId = new Guid("17cca59e-e2d7-4f53-ae8d-952297151463"),
                            ColorName = "Brown"
                        },
                        new
                        {
                            HeroId = new Guid("17cca59e-e2d7-4f53-ae8d-952297151463"),
                            ColorName = "Pink"
                        });
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroTraining", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HeroId", "TrainedAt");

                    b.ToTable("HeroTrainings");
                });

            modelBuilder.Entity("HeroesApi.Models.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "12ebb199-20ce-4eaf-b39c-7d7492877af6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1bdcf4d-b884-499f-95cf-f62b1aa16992",
                            Email = "user1@example.com",
                            EmailConfirmed = false,
                            FirstName = "Moshe",
                            LastName = "Cohen",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOcFTsgZYz8/P7PlFt/dW+3X6JLD0GDTcyXNM79ZtXUC7yH6vTr2m8+go8ONii3mCg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a721693-0275-448e-abd1-1d91c0661962",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = "b4dd9b01-acdb-4d17-855a-aeef45bb0892",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0bf91b64-4aa9-4964-ba81-a1c3914bca51",
                            Email = "user2@example.com",
                            EmailConfirmed = false,
                            FirstName = "Keren",
                            LastName = "David",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMo1s3Tb+3J5OhWvVSOuRWqYiYLGJ+s7tmtaGlc8UQ7pGARbF7VUN1GkX5mhOMx1rA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f6670aaa-ff05-4427-958f-ffe1b08bb152",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        },
                        new
                        {
                            Id = "62786193-15ce-4c5b-be9e-dff0e17fb15b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5d90166e-f9b0-4e21-86d5-b635b452fcfc",
                            Email = "user3@example.com",
                            EmailConfirmed = false,
                            FirstName = "Sholomo",
                            LastName = "Daniel",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER3@EXAMPLE.COM",
                            NormalizedUserName = "USER3@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEL+JgMo2bF4pBibprCKbRwYx/HNA1sp2Q9NI0N9QpjcK5x8VjAp5Jv1E8OsXgtb5Sw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d5c9bab0-1766-4b0b-baac-311ea35ce1c5",
                            TwoFactorEnabled = false,
                            UserName = "user3@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.Hero", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany("Heroes")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroSuitColor", b =>
                {
                    b.HasOne("HeroesApi.Models.Heroes.Hero", null)
                        .WithMany("SuitColors")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.HeroTraining", b =>
                {
                    b.HasOne("HeroesApi.Models.Heroes.Hero", null)
                        .WithMany("HeroTrainings")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HeroesApi.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesApi.Models.Heroes.Hero", b =>
                {
                    b.Navigation("HeroTrainings");

                    b.Navigation("SuitColors");
                });

            modelBuilder.Entity("HeroesApi.Models.IdentityModels.ApplicationUser", b =>
                {
                    b.Navigation("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
